openapi: 3.2.0
info:
  title: '@weka-api Default network API'
  version: '5.1'
  description: 'The WEKA system provides a RESTful API, enabling efficient

    automation and integration into existing workflows or monitoring systems.'
servers:
- url: /api/v2
security:
- bearerAuth: []
tags:
- name: Default network
paths:
  /defaultNet:
    get:
      tags:
      - Default network
      summary: Get default network
      operationId: getDefaultNetwork
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    properties:
                      range_available:
                        type: number
                        example: 255
                      range:
                        type: string
                        description: IP range (format - A.B.C.D-E.F.G.H or A.B.C.D-F.G.H or A.B.C.D-G.H or A.B.C.D-H).
                        example: 1.1.1.1-1.1.1.254
                      gateway:
                        type: string
                        description: Default gateway IP.
                        example: 255.255.255.255
                      netmask_bits:
                        type: number
                        description: Subnet mask bits (0..32).
                        example: 0
        '401':
          $ref: '#/components/responses/401'
    post:
      tags:
      - Default network
      summary: Set default network settings
      description: Defines the IP address range, gateway, and subnet mask for future container network assignments.
      operationId: setDefaultNetwork
      responses:
        '200':
          $ref: '#/components/responses/200'
        '401':
          $ref: '#/components/responses/401'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/defaultNet'
    put:
      tags:
      - Default network
      summary: Update default network settings
      description: Modifies existing default network settings, such as the IP range, gateway, or subnet mask.
      operationId: updateDefaultNetwork
      responses:
        '200':
          $ref: '#/components/responses/200'
        '401':
          $ref: '#/components/responses/401'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/defaultNet'
    delete:
      tags:
      - Default network
      summary: Reset default network settings
      description: Removes custom default network settings and reverts to the initial system baseline.
      operationId: resetDefaultNetwork
      responses:
        '200':
          $ref: '#/components/responses/200'
        '401':
          $ref: '#/components/responses/401'
components:
  responses:
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            properties:
              data:
                type: string
                example: Unauthorized
    '200':
      description: Success
      content:
        application/json:
          schema:
            properties:
              data:
                example: null
  schemas:
    defaultNet:
      type: object
      properties:
        range:
          type: string
          description: IP range (format - A.B.C.D-E.F.G.H or A.B.C.D-F.G.H or A.B.C.D-G.H or A.B.C.D-H)
          example: 1.1.1.1-1.1.1.254
        gateway:
          type: string
          description: Default gateway IP
          example: 255.255.255.255
        netmask:
          type: number
          description: Subnet mask bits (0..32)
          example: 0
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
