openapi: 3.2.0
info:
  title: '@weka-api Lockout policy API'
  version: '5.1'
  description: 'The WEKA system provides a RESTful API, enabling efficient

    automation and integration into existing workflows or monitoring systems.'
servers:
- url: /api/v2
security:
- bearerAuth: []
tags:
- name: Lockout Policy
paths:
  /lockoutPolicy:
    get:
      tags:
      - Lockout Policy
      summary: Get lockout policy
      description: Returns the account lockout threshold policy details.
      operationId: getLockoutPolicy
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/lockoutPolicy'
        '401':
          $ref: '#/components/responses/401'
    put:
      tags:
      - Lockout Policy
      summary: Update lockout policy
      description: Modifies the account lockout threshold policy.
      operationId: setLockoutPolicy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/lockoutPolicy'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/lockoutPolicy'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
    delete:
      tags:
      - Lockout Policy
      summary: Reset lockout policy
      description: Clears the failed login attempts counter and unlocks any currently locked accounts.
      operationId: resetLockoutPolicy
      responses:
        '200':
          $ref: '#/components/responses/200'
        '401':
          $ref: '#/components/responses/401'
components:
  responses:
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            properties:
              data:
                type: string
                example: Unauthorized
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: error message
              data:
                type: object
                properties:
                  missing_params:
                    type: array
                    items:
                      type: string
                      example: param1
                  param:
                    type: string
                    example: param2
                  error:
                    type: string
                    example: param2 has an error
    '200':
      description: Success
      content:
        application/json:
          schema:
            properties:
              data:
                example: null
  schemas:
    lockoutPolicy:
      type: object
      properties:
        num_failed_logins:
          type: number
          example: 5
        lockout_duration:
          type: number
          example: 120
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
