openapi: 3.2.0
info:
  title: '@weka-api Data Service API'
  version: '5.1'
  description: 'The WEKA system provides a RESTful API, enabling efficient

    automation and integration into existing workflows or monitoring systems.'
servers:
- url: /api/v2
security:
- bearerAuth: []
tags:
- name: Data Service
paths:
  /dataService/features:
    get:
      tags:
      - Data Service
      summary: List Data Service features
      description: Lists the background tasks, such as quota coloring, managed by the Data Services container.
      operationId: getFeatures
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/dataServiceFeatures'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
components:
  responses:
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            properties:
              data:
                type: string
                example: Unauthorized
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: error message
              data:
                type: object
                properties:
                  missing_params:
                    type: array
                    items:
                      type: string
                      example: param1
                  param:
                    type: string
                    example: param2
                  error:
                    type: string
                    example: param2 has an error
  schemas:
    dataServiceFeatures:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: quota
          enabled:
            type: boolean
            example: true
          description:
            type: string
            example: Distributed Quota
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
