openapi: 3.2.0
info:
  title: '@weka-api Health API'
  version: '5.1'
  description: 'The WEKA system provides a RESTful API, enabling efficient

    automation and integration into existing workflows or monitoring systems.'
servers:
- url: /api/v2
security:
- bearerAuth: []
tags:
- name: Health
paths:
  /healthcheck:
    get:
      tags:
      - Health
      summary: Check REST API status
      description: Verifies the availability of the REST API.
      operationId: getApiHealth
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
                example: ok
  /ui/healthcheck:
    get:
      tags:
      - Health
      summary: Check GUI status
      description: Verifies the availability of the GUI.
      operationId: getUIHealth
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
                example: ok
        '503':
          description: Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
